language: bash
os: linux

before_install:
  # To install bats-core for the testing infrastructure
  - git clone https://github.com/bats-core/bats-core.git
  - sudo ./bats-core/install.sh /usr/local
  - rm -rf ./bats-core

script:
  - cd ./client_side/.infrastructure
  - /usr/local/bin/bats --tap test

notifications:
  email:
    on_success: never
